FROM pytorch/pytorch:2.6.0-cuda12.4-cudnn9-runtime
WORKDIR /app
COPY pyproject.toml README.md ./
COPY src ./src
RUN pip install --no-cache-dir '.[train]'
COPY configs ./configs
ENV TOKENIZERS_PARALLELISM=false
ENTRYPOINT ["millst"]
CMD ["--config", "configs/main.yaml", "benchmark"]
